local Compress = require("Light.Plugins.Compress")
assert(Light.Plugins.Compress == Compress)
assert(type(Compress.Compress) == "function")
assert(type(Compress.Decompress) == "function")
assert(type(Compress.Deflate) == "function")
assert(type(Compress.Inflate) == "function")
assert(type(Compress.CRC32) == "function")
assert(type(Compress.Adler32) == "function")
assert(type(Compress.Version) == "function")

local raw = "hello hello hello" .. string.char(0, 1, 2, 255)
local packed = assert(Compress.Compress(raw, 6))
assert(type(packed) == "string" and #packed > 0)
assert(Compress.Decompress(packed) == raw)
assert(type(Compress.CRC32(raw)) == "number")
assert(type(Compress.Adler32(raw)) == "number")

local zlib = require("zlib")
assert(type(zlib.compress) == "function")
assert(type(zlib.decompress) == "function")
local packed2 = assert(zlib.compress(raw))
assert(zlib.decompress(packed2) == raw)

print("[smoke] compress ok")
