local Crypto = require("Light.Crypto")
assert(type(Crypto) == "table")
assert(Crypto.SHA1("abc") == "a9993e364706816aba3e25717850c26c9cd0d89d")
assert(#Crypto.SHA1_Raw("abc") == 20)
assert(Crypto.HexEncode(string.char(0, 255)) == "00ff")
assert(Crypto.HexEncode(string.char(0, 255), true) == "00FF")
assert(Crypto.HexDecode("00ff") == string.char(0, 255))
local bad, err = Crypto.HexDecode("abc")
assert(bad == nil and type(err) == "string")
assert(type(Crypto.CRC32("abc")) == "number")
print("[smoke] crypto utils ok")
