local Path = require("Light.Plugins.Path")
assert(Light.Plugins.Path == Path)
assert(type(Path.Join) == "function")
assert(type(Path.Normalize) == "function")
assert(type(Path.Basename) == "function")
assert(type(Path.Dirname) == "function")
assert(type(Path.Extname) == "function")
assert(type(Path.Stem) == "function")
assert(type(Path.IsAbsolute) == "function")
assert(type(Path.Split) == "function")
assert(type(Path.Separator) == "function")

local joined = Path.Join("foo", "bar", "baz.txt")
assert(joined:find("foo") and joined:find("bar") and joined:find("baz.txt"))
assert(Path.Normalize("foo//bar/./baz") == Path.Join("foo", "bar", "baz"))
assert(Path.Basename("foo/bar/baz.txt") == "baz.txt")
assert(Path.Dirname("foo/bar/baz.txt") == "foo/bar" or Path.Dirname("foo/bar/baz.txt") == "foo\\bar")
assert(Path.Extname("foo/bar/baz.txt") == ".txt")
assert(Path.Stem("foo/bar/baz.txt") == "baz")

local parts = Path.Split("foo/bar/baz.txt")
assert(type(parts) == "table" and #parts == 3)
assert(parts[1] == "foo" and parts[2] == "bar" and parts[3] == "baz.txt")

print("[smoke] path ok")
