---@diagnostic disable: undefined-global
--[[
  简易场景编辑器 Demo

  功能:
    - 工具栏: New / Save / Add Sprite / Add Box / Clear
    - 画布: 可拖动的对象 (sprite / box)
    - 选中: 点击对象高亮, 可编辑属性
    - 属性面板: 显示选中对象的 x/y/w/h/color, 可调整
    - 保存: 序列化为 Lua 表 (输出到控制台)

  涉及模块:
    Light.UI.Widget — 容器/按钮/标签/面板
    Light.Graphics  — 自定义绘制 (selected 高亮框)
]]

require("Light.UI.Window")
require("Light.Graphics")
require("Light.UI.Widget")

local Widget = Light.UI.Widget

-- ============================================================
-- 编辑器状态
-- ============================================================
local Editor = {
  W = 1200, H = 700,
  TOOLBAR_H   = 40,
  SIDEBAR_W   = 240,
  CANVAS_X    = 0,
  CANVAS_Y    = 40,
  CANVAS_W    = nil,  -- 启动时算
  CANVAS_H    = nil,
}
Editor.CANVAS_W = Editor.W - Editor.SIDEBAR_W
Editor.CANVAS_H = Editor.H - Editor.TOOLBAR_H

-- 编辑对象列表 (PlainData, 易序列化)
local objects = {}     -- { {type='box', x=, y=, w=, h=, color={r,g,b}}, ... }
local selected = nil   -- 选中对象索引
local dragging = nil   -- {idx, dx, dy}  正在拖动

-- ============================================================
-- 业务逻辑
-- ============================================================
local function colorPalette(idx)
  local palette = {
    {0.9, 0.4, 0.4},  -- 红
    {0.4, 0.9, 0.4},  -- 绿
    {0.4, 0.6, 0.95}, -- 蓝
    {0.95, 0.85, 0.3},-- 黄
    {0.8, 0.5, 0.95}, -- 紫
    {0.4, 0.9, 0.85}, -- 青
  }
  return palette[((idx - 1) % #palette) + 1]
end

local function addBox()
  local id = #objects + 1
  objects[id] = {
    type = 'box',
    x = math.random(50, Editor.CANVAS_W - 100),
    y = math.random(50, Editor.CANVAS_H - 100),
    w = 60, h = 60,
    color = colorPalette(id),
  }
  selected = id
end

local function clearAll()
  objects   = {}
  selected  = nil
  dragging  = nil
end

-- 命中测试 (画布坐标系内)
local function pickAt(cx, cy)
  -- 倒序遍历, 后画的在上层
  for i = #objects, 1, -1 do
    local o = objects[i]
    if cx >= o.x and cx <= o.x + o.w and cy >= o.y and cy <= o.y + o.h then
      return i
    end
  end
  return nil
end

-- 序列化为 Lua 字符串
local function serialize()
  local lines = {"-- Auto-generated by ChocoLight Scene Editor", "return {"}
  for i, o in ipairs(objects) do
    lines[#lines+1] = string.format(
      "  {type=%q, x=%d, y=%d, w=%d, h=%d, color={%.2f,%.2f,%.2f}},",
      o.type, o.x, o.y, o.w, o.h, o.color[1], o.color[2], o.color[3])
  end
  lines[#lines+1] = "}"
  return table.concat(lines, "\n")
end

-- ============================================================
-- 自定义绘制控件: Canvas (覆盖 Draw 方法)
-- ============================================================
local function NewCanvas(x, y, w, h)
  local self = Widget.Container.New(x, y, w, h)
  self.Draw = function(self_)
    -- 背景
    Light.Graphics.SetColor(0.12, 0.12, 0.14, 1)
    Light.Graphics.Rectangle(2, self_.x, self_.y, self_.w, self_.h, 0)
    -- 网格
    Light.Graphics.SetColor(0.18, 0.18, 0.22, 1)
    for gx = 0, self_.w, 40 do
      Light.Graphics.Line(self_.x + gx, self_.y, 0, self_.x + gx, self_.y + self_.h, 0)
    end
    for gy = 0, self_.h, 40 do
      Light.Graphics.Line(self_.x, self_.y + gy, 0, self_.x + self_.w, self_.y + gy, 0)
    end
    -- 对象
    for i, o in ipairs(objects) do
      local ox = self_.x + o.x
      local oy = self_.y + o.y
      Light.Graphics.SetColor(o.color[1], o.color[2], o.color[3], 1)
      Light.Graphics.Rectangle(2, ox, oy, o.w, o.h, 0)
      -- 选中边框
      if i == selected then
        Light.Graphics.SetColor(1, 1, 0, 1)
        Light.Graphics.Rectangle(1, ox - 2, oy - 2, o.w + 4, o.h + 4, 0)
      end
    end
    -- 边框
    Light.Graphics.SetColor(0.4, 0.4, 0.5, 1)
    Light.Graphics.Rectangle(1, self_.x, self_.y, self_.w, self_.h, 0)
  end
  
  -- 鼠标事件: 转为画布坐标后处理对象
  self.OnMouseDown = function(self_, mx, my, btn)
    local cx = mx - self_.x
    local cy = my - self_.y
    local hit = pickAt(cx, cy)
    if hit then
      selected = hit
      dragging = { idx = hit, dx = cx - objects[hit].x, dy = cy - objects[hit].y }
    else
      selected = nil
      dragging = nil
    end
  end
  self.OnMouseMove = function(self_, mx, my)
    if dragging then
      local cx = mx - self_.x
      local cy = my - self_.y
      objects[dragging.idx].x = cx - dragging.dx
      objects[dragging.idx].y = cy - dragging.dy
    end
  end
  self.OnMouseUp = function(self_, mx, my, btn)
    dragging = nil
  end
  return self
end

-- ============================================================
-- 自定义绘制控件: 属性面板 (动态显示 selected)
-- ============================================================
local function NewPropertyPanel(x, y, w, h)
  local self = Widget.Panel.New(x, y, w, h, {
    bgColor     = {0.18, 0.18, 0.22, 1},
    borderColor = {0.4, 0.4, 0.5, 1},
  })
  
  -- 覆写 Draw 添加内容
  local origDraw = self.Draw
  self.Draw = function(self_)
    origDraw(self_)
    Light.Graphics.SetColor(1, 1, 1, 1)
    Light.Graphics.Print("Properties", nil, self_.x + 12, self_.y + 12, 0)
    Light.Graphics.SetColor(0.5, 0.5, 0.55, 1)
    Light.Graphics.Line(self_.x + 8, self_.y + 30, 0, self_.x + self_.w - 8, self_.y + 30, 0)

    if selected and objects[selected] then
      local o = objects[selected]
      local lines = {
        string.format("Index: #%d", selected),
        string.format("Type:  %s", o.type),
        string.format("X:     %d", o.x),
        string.format("Y:     %d", o.y),
        string.format("W:     %d", o.w),
        string.format("H:     %d", o.h),
        string.format("Color: %.2f, %.2f, %.2f", o.color[1], o.color[2], o.color[3]),
      }
      Light.Graphics.SetColor(0.85, 0.85, 0.9, 1)
      for i, line in ipairs(lines) do
        Light.Graphics.Print(line, nil, self_.x + 12, self_.y + 40 + (i - 1) * 22, 0)
      end
      
      -- 操作提示
      Light.Graphics.SetColor(0.6, 0.6, 0.65, 1)
      Light.Graphics.Print("Drag to move", nil, self_.x + 12, self_.y + 40 + 8 * 22, 0)
      Light.Graphics.Print("Del key: remove", nil, self_.x + 12, self_.y + 40 + 9 * 22, 0)
    else
      Light.Graphics.SetColor(0.55, 0.55, 0.6, 1)
      Light.Graphics.Print("(Click an object", nil, self_.x + 12, self_.y + 50, 0)
      Light.Graphics.Print(" in the canvas)", nil, self_.x + 12, self_.y + 72, 0)
    end
    
    -- 对象总数
    Light.Graphics.SetColor(0.5, 0.7, 0.5, 1)
    Light.Graphics.Print("Total: " .. #objects, nil, self_.x + 12, self_.y + self_.h - 30, 0)
  end
  return self
end

-- ============================================================
-- 主窗口
-- ============================================================
local App = Light(Light.UI.Window):New()

function App:OnOpen()
  -- 工具栏背景
  self.toolbar = Widget.Panel.New(0, 0, Editor.W, Editor.TOOLBAR_H, {
    bgColor     = {0.20, 0.22, 0.27, 1},
    borderColor = {0.4, 0.4, 0.5, 1},
  })

  -- 按钮
  self.btnAdd = Widget.Button.New(8, 5, 110, 30, "+ Add Box", {
    OnClick = function() addBox() end,
  })
  self.btnClr = Widget.Button.New(124, 5, 90, 30, "Clear", {
    OnClick = function() clearAll() end,
  })
  self.btnSave = Widget.Button.New(220, 5, 110, 30, "Save (stdout)", {
    OnClick = function()
      print("---- Saved scene ----")
      print(serialize())
      print("---- End ----")
    end,
  })
  self.btnRandom10 = Widget.Button.New(336, 5, 130, 30, "+ Random 10", {
    OnClick = function() for i=1,10 do addBox() end end,
  })

  -- 画布
  self.canvas = NewCanvas(Editor.CANVAS_X, Editor.CANVAS_Y, Editor.CANVAS_W, Editor.CANVAS_H)

  -- 属性面板
  self.props = NewPropertyPanel(Editor.W - Editor.SIDEBAR_W, Editor.TOOLBAR_H,
                                Editor.SIDEBAR_W, Editor.CANVAS_H)

  -- 根容器
  self.root = Widget.Container.New(0, 0, Editor.W, Editor.H)
  self.root:AddChild(self.toolbar)
  self.toolbar:AddChild(self.btnAdd)
  self.toolbar:AddChild(self.btnClr)
  self.toolbar:AddChild(self.btnSave)
  self.toolbar:AddChild(self.btnRandom10)
  self.root:AddChild(self.canvas)
  self.root:AddChild(self.props)
  
  -- 标题在工具栏右侧
  self.title = Widget.Label.New(480, 13, "ChocoLight Scene Editor",
    { color = {0.7, 0.85, 0.9, 1.0} })
  self.toolbar:AddChild(self.title)

  -- 初始化几个示例对象
  for i = 1, 3 do addBox() end
  selected = nil

  math.randomseed(os.time and os.time() or 1)
  print("[Editor] ready. Drag boxes; click Save to print Lua data.")
end

function App:Update(dt)
  self.root:Update(dt)
end

function App:Draw()
  -- 整体背景
  Light.Graphics.SetColor(0.08, 0.08, 0.10, 1)
  Light.Graphics.Rectangle(2, 0, 0, Editor.W, Editor.H, 0)
  self.root:Draw()
end

function App:OnKey(key, scanCode, action, mods)
  if action ~= 1 then return end
  if key == 261 or key == 127 then  -- Delete
    if selected then
      table.remove(objects, selected)
      selected = nil
    end
  end
end

function App:OnMouseButton(x, y, button, action, mods)
  if action == 1 then
    self.root:Dispatch("OnMouseDown", x, y, button)
  else
    self.root:Dispatch("OnMouseUp", x, y, button)
  end
end

function App:OnMousePosition(x, y)
  self.root:Dispatch("OnMouseMove", x, y)
end

App:Open(Editor.W, Editor.H, "ChocoLight Scene Editor")
App:SetVSync(true)

while Light.UI.Loop() do
  Light.UI.Resume()
end
