/*!
 * @brief Lua stand-alone interpreter
 * @author Lua.org, PUC-Rio, Jakit (https://github.com/jakitliang/lumen)
 * @date 2025/5/13
 * @copyright
 * Copyright (c) 2025 Lua.org, PUC-Rio, Jakit. All rights reserved.
 * Licensed under the BSD 2-Clause License.
 */


#include <csignal>
#include <cstdio>
#include <cstdlib>
#include <cstring>

#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
// windows.h 的 Yield 宏与 Lumen::IState::Yield() 冲突
#undef Yield
#elif defined(__APPLE__)
#include <mach-o/dyld.h>  // _NSGetExecutablePath
#include <dlfcn.h>
#elif defined(__linux__) || defined(__ANDROID__)
#include <unistd.h>       // readlink
#include <dlfcn.h>
#endif

#define lumen_c

#include "lumen.h"

// Embedded Lua scripts (generated by lua2header.py)
// Header defines HAS_EMBEDDED_SCRIPTS=0 or 1 based on content
#include "embedded_scripts.h"
#ifndef HAS_EMBEDDED_SCRIPTS
#define HAS_EMBEDDED_SCRIPTS 0
#endif

#define lua_assert(c) ((void) 0)

/*
 * lua_stdin_is_tty detects whether the standard input is a 'tty' (that
 * is, whether we're running lua interactively).
 * CHANGE it if you have a better definition for non-POSIX/non-Windows
 * systems.
 */
#if defined(LUA_USE_ISATTY)
LUA_C_BEGIN
#include <unistd.h>
LUA_C_END
#define lua_stdin_is_tty()	isatty(0)
#elif defined(LUA_WIN)
#include <io.h>
#define lua_stdin_is_tty()    _isatty(_fileno(stdin))
#else
#define lua_stdin_is_tty()	1  /* assume stdin is a tty */
#endif

/*
 * lua_readline defines how to show a prompt and then read a line from
 * the standard input.
 * lua_saveline defines how to "save" a read line in a "history".
 * lua_freeline defines how to free a line read by lua_readline.
 * CHANGE them if you want to improve this functionality (e.g., by using
 * GNU readline and history facilities).
 */
#if defined(LUA_USE_READLINE)
LUA_C_BEGIN
#include <readline/readline.h>
#include <readline/history.h>
LUA_C_END
#define lua_readline(L,b,p)	((void)L, ((b)=readline(p)) != nullptr)
#define lua_saveline(L,idx) \
    if (L->StringLength(idx) > 0)  /* non-empty line? */ \
      add_history(L->ToString(idx));  /* add it to history */
#define lua_freeline(L,b)	((void)L, free(b))
#else
#define lua_readline(L, b, p)    \
    ((void)L, fputs(p, stdout), fflush(stdout),  /* show prompt */ \
    fgets(b, LUA_MAX_INPUT, stdin) != nullptr)  /* get line */
#define lua_saveline(L, idx)    do { (void)L; (void)idx; } while (0)
#define lua_freeline(L, b)    do { (void)L; (void)b; } while (0)
#endif

static Lumen::IState *globalL = nullptr;

static const char *programName = LUA_PROGRAM_NAME;


static void luaStop(Lumen::IState *L, Lumen::DebugInfo *) {
//    (void) ar;  /* unused arg. */
    L->SetHook(nullptr, 0, 0);
    L->Error("interrupted!");
}


static void luaAction(int i) {
    signal(i, SIG_DFL); /* if another SIGINT happens before luaStop,
                              terminate process (default action) */
    globalL->SetHook(luaStop, Lumen::HookMaskCall | Lumen::HookMaskRet | Lumen::HookMaskCount, 1);
}


static void printUsage() {
    fprintf(stderr,
            "usage: %s [options] [script [args]].\n"
            "Available options are:\n"
            "  -e stat  execute string " LUA_QL("stat") "\n"
            "  -l name  require library " LUA_QL("name") "\n"
            "  -i       enter interactive mode after executing " LUA_QL("script") "\n"
            "  -v       show version information\n"
            "  --       stop handling options\n"
            "  -        execute stdin and stop handling options\n",
            programName);
    fflush(stderr);
}


static void luaMessage(const char *pName, const char *msg) {
    if (pName) fprintf(stderr, "%s: ", pName);
    fprintf(stderr, "%s\n", msg);
    fflush(stderr);
}


static int report(Lumen::IState *L, int status) {
    if (status && !L->IsNil(-1)) {
        const char *msg = L->ToString(-1);
        if (msg == nullptr) msg = "(error object is not a string)";
        luaMessage(programName, msg);
        L->Pop(1);
    }
    return status;
}


static int traceback(Lumen::IState *L) {
    if (!L->IsString(1))  /* 'message' not a string? */
        return 1;  /* keep it intact */
    L->GetField(Lumen::GlobalIndex, "debug");
    if (!L->IsTable(-1)) {
        L->Pop(1);
        return 1;
    }
    L->GetField(-1, "traceback");
    if (!L->IsFunction(-1)) {
        L->Pop(2);
        return 1;
    }
    L->PushValue(1);  /* pass error message */
    L->PushInteger(2);  /* skip this function and traceback */
    L->Call(2, 1);  /* call debug.traceback */
    return 1;
}


static int doCall(Lumen::IState *L, int nArg, int clear) {
    int status;
    int base = L->GetTop() - nArg;  /* function index */
    L->PushDelegate(traceback);  /* push traceback function */
    L->Insert(base);  /* put it under chunk and args */
    signal(SIGINT, luaAction);
    status = L->TryCall(nArg, (clear ? 0 : Lumen::RetMul), base);
    signal(SIGINT, SIG_DFL);
    L->Remove(base);  /* remove traceback function */
    /* force a complete garbage collection in case of errors */
    if (status != 0) L->GC(Lumen::GCCollect, 0);
    return status;
}


static void printVersion() {
    luaMessage(nullptr, LUMEN_RELEASE " -- " LUMEN_COPYRIGHT);
}


static int getArgs(Lumen::IState *L, char **argv, int n) {
    int nArg;
    int i;
    int argc = 0;
    while (argv[argc]) argc++;  /* count total number of arguments */
    nArg = argc - (n + 1);  /* number of arguments to the script */
    L->CheckStack(nArg + 3, "too many arguments to script");
    for (i = n + 1; i < argc; i++)
        L->PushString(argv[i]);
    L->CreateTable(nArg, n + 1);
    for (i = 0; i < argc; i++) {
        L->PushString(argv[i]);
        L->RawSetAt(-2, i - n);
    }
    return nArg;
}


static int doFile(Lumen::IState *L, const char *name) {
    int status = L->LoadFile(name) || doCall(L, 0, 1);
    return report(L, status);
}


static int doString(Lumen::IState *L, const char *s, const char *name) {
    int status = L->LoadBuffer(s, strlen(s), name) || doCall(L, 0, 1);
    return report(L, status);
}


static int doLibrary(Lumen::IState *L, const char *name) {
    L->GetGlobal("require");
    L->PushString(name);
    return report(L, doCall(L, 1, 1));
}


static const char *getPrompt(Lumen::IState *L, int firstLine) {
    const char *p;
    L->GetField(Lumen::GlobalIndex, firstLine ? "_PROMPT" : "_PROMPT2");
    p = L->ToString(-1);
    if (p == nullptr) p = (firstLine ? LUA_PROMPT : LUA_PROMPT2);
    L->Pop(1);  /* remove global */
    return p;
}


static int inComplete(Lumen::IState *L, int status) {
    if (status == Lumen::RetErrSyntax) {
        size_t msgLength;
        const char *msg = L->ToString(-1, &msgLength);
        const char *tp = msg + msgLength - (sizeof(LUA_QL("<eof>")) - 1);
        if (strstr(msg, LUA_QL("<eof>")) == tp) {
            L->Pop(1);
            return 1;
        }
    }
    return 0;  /* else... */
}


static int pushLine(Lumen::IState *L, int firstLine) {
    char buffer[LUA_MAX_INPUT];
    char *b = buffer;
    size_t l;
    const char *prompt = getPrompt(L, firstLine);
    if (lua_readline(L, b, prompt) == 0)
        return 0;  /* no input */
    l = strlen(b);
    if (l > 0 && b[l - 1] == '\n')  /* line ends with newline? */
        b[l - 1] = '\0';  /* remove it */
    if (firstLine && b[0] == '=')  /* first line starts with `=` ? */
        L->PushFString("return %s", b + 1);  /* change it to `return` */
    else
        L->PushString(b);
    lua_freeline(L, b);
    return 1;
}


static int loadLine(Lumen::IState *L) {
    int status;
    L->SetTop(0);
    if (!pushLine(L, 1))
        return -1;  /* no input */
    for (;;) {  /* repeat until gets a complete line */
        status = L->LoadBuffer(L->ToString(1), L->StringLength(1), "=stdin");
        if (!inComplete(L, status)) break;  /* cannot try to add lines? */
        if (!pushLine(L, 0))  /* no more input? */
            return -1;
        L->PushLiteral("\n");  /* add a new line... */
        L->Insert(-2);  /* ...between the two lines */
        L->Concat(3);  /* join them */
    }
    lua_saveline(L, 1);
    L->Remove(1);  /* remove line */
    return status;
}


static void dotty(Lumen::IState *L) {
    int status;
    const char *oldProgramName = programName;
    programName = nullptr;
    while ((status = loadLine(L)) != -1) {
        if (status == 0) status = doCall(L, 0, 0);
        report(L, status);
        if (status == 0 && L->GetTop() > 0) {  /* any result to print? */
            L->GetGlobal("print");
            L->Insert(1);
            if (L->TryCall(L->GetTop() - 1, 0, 0) != 0)
                luaMessage(programName, L->PushFString("error calling " LUA_QL("print") " (%s)",
                                                       L->ToString(-1)));
        }
    }
    L->SetTop(0);  /* clear stack */
    fputs("\n", stdout);
    fflush(stdout);
    programName = oldProgramName;
}


static int handleScript(Lumen::IState *L, char **argv, int n) {
    int status;
    const char *fileName;
    int nArg = getArgs(L, argv, n);  /* collect arguments */
    L->SetGlobal("arg");
    fileName = argv[n];
    if (strcmp(fileName, "-") == 0 && strcmp(argv[n - 1], "--") != 0)
        fileName = nullptr;  /* stdin */
    status = L->LoadFile(fileName);
    L->Insert(-(nArg + 1));
    if (status == 0)
        status = doCall(L, nArg, 0);
    else
        L->Pop(nArg);
    return report(L, status);
}


/* check that argument has no extra characters at the end */
#define noTail(x)   do { if ((x)[2] != '\0') return -1; } while (0)


static int collectArgs(char **argv, int *pi, int *pv, int *pe) {
    int i;
    for (i = 1; argv[i] != nullptr; i++) {
        if (argv[i][0] != '-')  /* not an option? */
            return i;
        switch (argv[i][1]) {  /* option */
            case '-':
                noTail(argv[i]);
                return (argv[i + 1] != nullptr ? i + 1 : 0);
            case '\0':
                return i;
            case 'i':
                noTail(argv[i]);
                *pi = 1;  /* go through */
            case 'v':
                noTail(argv[i]);
                *pv = 1;
                break;
            case 'e':
                *pe = 1;  /* go through */
            case 'l':
                if (argv[i][2] == '\0') {
                    i++;
                    if (argv[i] == nullptr) return -1;
                }
                break;
            default:
                return -1;  /* invalid option */
        }
    }
    return 0;
}


static int runArgs(Lumen::IState *L, char **argv, int n) {
    int i;
    for (i = 1; i < n; i++) {
        if (argv[i] == nullptr) continue;
        lua_assert(argv[i][0] == '-');
        switch (argv[i][1]) {  /* option */
            case 'e': {
                const char *chunk = argv[i] + 2;
                if (*chunk == '\0') chunk = argv[++i];
                lua_assert(chunk != nullptr);
                if (doString(L, chunk, "=(command line)") != 0)
                    return 1;
                break;
            }
            case 'l': {
                const char *filename = argv[i] + 2;
                if (*filename == '\0') filename = argv[++i];
                lua_assert(filename != nullptr);
                if (doLibrary(L, filename))
                    return 1;  /* stop if file fails */
                break;
            }
            default:
                break;
        }
    }
    return 0;
}


static int handleLuaInit(Lumen::IState *L) {
    const char *init = getenv(LUA_INIT);
    if (init == nullptr) return 0;  /* status OK */
    else if (init[0] == '@')
        return doFile(L, init + 1);
    else
        return doString(L, init, "=" LUA_INIT);
}


struct MainArgs {
    int argc;
    char **argv;
    int status;
};


// ==================== Light.dll engine auto-preload ====================
// Dynamically load Light.dll from exe directory and preload all luaopen_* modules

#ifdef _WIN32

// Module mapping table: { require name, DLL export name }
static const struct { const char *modName; const char *procName; } g_lightModules[] = {
    {"Light",                     "luaopen_Light"},
    {"Light.Debug",               "luaopen_Light_Debug"},
    {"Light.Data",                "luaopen_Light_Data"},
    {"Light.Math",                "luaopen_Light_Math"},
    {"Light.UI",                  "luaopen_Light_UI"},
    {"Light.UI.Window",           "luaopen_Light_UI_Window"},
    {"Light.UI.Widget",           "luaopen_Light_UI_Widget"},
    {"Light.Graphics",            "luaopen_Light_Graphics"},
    {"Light.Graphics.Canvas",     "luaopen_Light_Graphics_Canvas"},
    {"Light.Graphics.Image",      "luaopen_Light_Graphics_Image"},
    {"Light.Graphics.ImageData",  "luaopen_Light_Graphics_ImageData"},
    {"Light.Graphics.Font",       "luaopen_Light_Graphics_Font"},
    {"Light.Graphics.PixelFormat","luaopen_Light_Graphics_PixelFormat"},
    {"Light.Graphics.Particles",  "luaopen_Light_Graphics_Particles"},
    {"Light.Graphics.Tilemap",    "luaopen_Light_Graphics_Tilemap"},
    {"Light.Graphics.SpriteAnimation", "luaopen_Light_Graphics_SpriteAnimation"},
    {"Light.Graphics.Shader",     "luaopen_Light_Graphics_Shader"},
    {"Light.AV",                  "luaopen_Light_AV"},
    {"Light.AV.Audio",            "luaopen_Light_AV_Audio"},
    {"Light.AV.AudioData",        "luaopen_Light_AV_AudioData"},
    {"Light.AV.Video",            "luaopen_Light_AV_Video"},
    {"Light.DB",                  "luaopen_Light_DB"},
    {"Light.DB.SQLite",           "luaopen_Light_DB_SQLite"},
    {"Light.Network",             "luaopen_Light_Network"},
    {"Light.Network.Http",        "luaopen_Light_Network_Http"},
    {"Light.Network.HttpServer",  "luaopen_Light_Network_HttpServer"},
    {"Light.Network.Web",         "luaopen_Light_Network_Web"},
    {"Light.Input",               "luaopen_Light_Input"},
    {"Light.Physics",             "luaopen_Light_Physics"},
    {"Light.Physics.World",       "luaopen_Light_Physics_World"},
    {"Light.ECS",                 "luaopen_Light_ECS"},
    {"Light.Scene",               "luaopen_Light_Scene"},
    {"Light.HotReload",           "luaopen_Light_HotReload"},
    {"Light.Crypto",              "luaopen_Light_Crypto"},
    {"Light.IO",                  "luaopen_Light_IO"},
    {"Light.Storage",             "luaopen_Light_Storage"},
    {"Light.Locale",              "luaopen_Light_Locale"},
    {"Light.Power",               "luaopen_Light_Power"},
    {"Light.Sensor",              "luaopen_Light_Sensor"},
    {"Light.Process",             "luaopen_Light_Process"},
    {"Light.Camera",              "luaopen_Light_Camera"},
    {"Light.MessageBox",          "luaopen_Light_MessageBox"},
    {"Light.Clipboard",           "luaopen_Light_Clipboard"},
    {"Light.URL",                 "luaopen_Light_URL"},
    {"Light.Display",             "luaopen_Light_Display"},
    {"Light.Cursor",              "luaopen_Light_Cursor"},
    {"Light.Gamepad",             "luaopen_Light_Gamepad"},
    {"Light.Guid",                "luaopen_Light_Guid"},
    {"Light.System",              "luaopen_Light_System"},
    {"Light.Tray",                "luaopen_Light_Tray"},
    {"Light.Hidapi",              "luaopen_Light_Hidapi"},
    {"Light.Haptic",              "luaopen_Light_Haptic"},
    {"Light.Dialog",              "luaopen_Light_Dialog"},
    {"Light.Touch",               "luaopen_Light_Touch"},
    {"Light.Hints",               "luaopen_Light_Hints"},
    {"Light.Time",                "luaopen_Light_Time"},
    {"Light.Endian",              "luaopen_Light_Endian"},
    {"Light.Log",                 "luaopen_Light_Log"},
    {"Light.Pixels",              "luaopen_Light_Pixels"},
    {"Light.BlendMode",           "luaopen_Light_BlendMode"},
    {"Light.Filesystem",          "luaopen_Light_Filesystem"},
    {"Light.CPUInfo",             "luaopen_Light_CPUInfo"},
    {"Light.Error",               "luaopen_Light_Error"},
    {"Light.Loadso",              "luaopen_Light_Loadso"},
    {"Light.Version",             "luaopen_Light_Version"},
    {"Light.Properties",          "luaopen_Light_Properties"},
    {"Light.Misc",                "luaopen_Light_Misc"},
    {"Light.Rect",                "luaopen_Light_Rect"},
    {"Light.Atomic",              "luaopen_Light_Atomic"},
    {"Light.Mutex",               "luaopen_Light_Mutex"},
    {"Light.IOStream",            "luaopen_Light_IOStream"},
    {"Light.Surface",             "luaopen_Light_Surface"},
    {"Light.Keyboard",            "luaopen_Light_Keyboard"},
    {"Light.Mouse",               "luaopen_Light_Mouse"},
    {"Light.Joystick",            "luaopen_Light_Joystick"},
    {"Light.Audio",               "luaopen_Light_Audio"},
    {"Light.Record",              "luaopen_Light_Record"},
    {"Light.Plugins",             "luaopen_Light_Plugins"},
    {"Light.Plugins.WDFData",     "luaopen_Light_Plugins_WDFData"},
    {"Light.Plugins.NEMData",     "luaopen_Light_Plugins_NEMData"},
    {"Light.Event",               "luaopen_Light_Event"},
    {"Light.Graphics.Mesh",       "luaopen_Light_Graphics_Mesh"},
    {"Light.Graphics.Material",   "luaopen_Light_Graphics_Material"},
    // Phase AT — Audio 3D 空间化 + Mixer + Effects
    {"Light.Audio.Sound",         "luaopen_Light_Audio_Sound"},
    {"Light.Audio.SoundGroup",    "luaopen_Light_Audio_SoundGroup"},
    {"Light.Audio.Effect",        "luaopen_Light_Audio_Effect"},
    // Phase AU — 3D Physics (Bullet 3)
    {"Light.Physics3D",           "luaopen_Light_Physics3D"},
    // Phase AV — Skeletal Animation + State Machine
    {"Light.Animation",           "luaopen_Light_Animation"},
    {"Light.Animation.Skeleton",  "luaopen_Light_Animation_Skeleton"},
    {"Light.Animation.Clip",      "luaopen_Light_Animation_Clip"},
    {"Light.Animation.Animator",  "luaopen_Light_Animation_Animator"},
    {nullptr, nullptr}
};

// Load Light.dll from exe directory and preload all engine modules
static void loadLightEngine(Lumen::IState *L) {
    // Build path: <exe_dir>/Light.dll
    char dllPath[MAX_PATH];
    DWORD pathLen = GetModuleFileNameA(nullptr, dllPath, MAX_PATH);
    if (pathLen == 0) return;

    // Find last path separator
    char *sep = strrchr(dllPath, '\\');
    if (!sep) sep = strrchr(dllPath, '/');
    if (sep) *(sep + 1) = '\0';
    else dllPath[0] = '\0';
    strncat(dllPath, "Light.dll", MAX_PATH - strlen(dllPath) - 1);

    HMODULE hLight = LoadLibraryA(dllPath);
    if (!hLight) return;  // Light.dll not found, skip silently

    int count = 0;
    for (int i = 0; g_lightModules[i].modName; ++i) {
        auto proc = (Lumen::Function)GetProcAddress(hLight, g_lightModules[i].procName);
        if (proc) {
            L->Require(g_lightModules[i].modName, proc);
            ++count;
        }
    }

    if (count > 0) {
        fprintf(stdout, "[Light] Engine loaded: %d modules from %s\n", count, dllPath);
        fflush(stdout);
    }
}

#endif // _WIN32 — loadLightEngine is Windows-only

// ==================== Pack Header: load encrypted script from exe tail ====================
// Format: [exe][encrypted payload][128-byte header with LMPK magic]

static const int LMPK_HEADER_SIZE = 128;
static const int LMPK_OPCODE_COUNT = 38;
static const int LMPK_XOR_KEY_MAX = 64;
static const unsigned int LMPK_MAGIC = 0x4B504D4C; // "LMPK" little-endian

// Master key (obfuscated: each byte XOR'd with its index)
// Matches lightpack.py _MK_ENC
static const unsigned char g_mkEnc[] = {
    0x43^0, 0x68^1, 0x6F^2, 0x63^3, 0x6F^4, 0x4C^5, 0x69^6, 0x67^7,
    0x68^8, 0x74^9, 0x32^10, 0x30^11, 0x32^12, 0x36^13, 0x21^14, 0x40^15,
    0x23^16
};
static const int g_mkLen = sizeof(g_mkEnc);

static unsigned char deobfMK(int i) {
    return g_mkEnc[i] ^ (unsigned char)i;
}

// Remap opcodes in a Lua 5.1 function prototype (recursive)
static void remapProtoOpcodes(unsigned char *buf, int &pos, int len,
                              const unsigned char *revPerm, int szT) {
    auto readByte = [&]() -> int { return (pos < len) ? buf[pos++] : 0; };
    auto readInt = [&]() -> int {
        if (pos + 4 > len) { pos = len; return 0; }
        int v; memcpy(&v, buf + pos, 4); pos += 4; return v;
    };
    auto readNumber = [&]() { pos += 8; };
    auto readString = [&]() {
        if (pos + szT > len) { pos = len; return; }
        size_t sz = 0;
        memcpy(&sz, buf + pos, szT); pos += szT;
        pos += (int)sz;
    };

    readString(); // source name
    readInt(); readInt(); // line defined, last line
    readByte(); readByte(); readByte(); readByte(); // nups, params, vararg, stack

    // Instructions: remap opcode field (bits 0-5)
    int numInstr = readInt();
    int instrStart = pos;
    for (int i = 0; i < numInstr && instrStart + i*4 + 4 <= len; ++i) {
        unsigned int instr;
        memcpy(&instr, buf + instrStart + i*4, 4);
        unsigned int oldOp = instr & 0x3F;
        if (oldOp < (unsigned)LMPK_OPCODE_COUNT) {
            unsigned int newOp = revPerm[oldOp];
            instr = (instr & ~0x3Fu) | newOp;
            memcpy(buf + instrStart + i*4, &instr, 4);
        }
    }
    pos = instrStart + numInstr * 4;

    // Constants
    int numK = readInt();
    for (int i = 0; i < numK; ++i) {
        int t = readByte();
        if (t == 1) readByte();       // boolean
        else if (t == 3) readNumber(); // number
        else if (t == 4) readString(); // string
    }

    // Inner prototypes (recursive)
    int numP = readInt();
    for (int i = 0; i < numP; ++i)
        remapProtoOpcodes(buf, pos, len, revPerm, szT);

    // Debug: lineinfo, locals, upvalues
    int numLine = readInt(); pos += numLine * 4;
    int numLoc = readInt();
    for (int i = 0; i < numLoc; ++i) { readString(); readInt(); readInt(); }
    int numUp = readInt();
    for (int i = 0; i < numUp; ++i) readString();
}

// Try to load packed script from exe's own file tail
static int loadPackedScript(Lumen::IState *L) {
    char exePath[4096];
#ifdef _WIN32
    if (GetModuleFileNameA(nullptr, exePath, sizeof(exePath)) == 0) return -1;
#elif defined(__APPLE__)
    uint32_t epSize = sizeof(exePath);
    if (_NSGetExecutablePath(exePath, &epSize) != 0) return -1;
#elif defined(__linux__) || defined(__ANDROID__)
    ssize_t len = readlink("/proc/self/exe", exePath, sizeof(exePath) - 1);
    if (len <= 0) return -1;
    exePath[len] = '\0';
#else
    return -1; // unsupported platform
#endif

    FILE *f = fopen(exePath, "rb");
    if (!f) return -1;

    // Read 128-byte header from tail
    fseek(f, 0, SEEK_END);
    long fileSize = ftell(f);
    if (fileSize < LMPK_HEADER_SIZE + 16) { fclose(f); return -1; }

    unsigned char hdr[LMPK_HEADER_SIZE];
    fseek(f, fileSize - LMPK_HEADER_SIZE, SEEK_SET);
    if (fread(hdr, 1, LMPK_HEADER_SIZE, f) != LMPK_HEADER_SIZE) { fclose(f); return -1; }

    // Check magic
    unsigned int magic;
    memcpy(&magic, hdr, 4);
    if (magic != LMPK_MAGIC) { fclose(f); return -1; }

    // Parse header fields
    unsigned int payloadSize;
    memcpy(&payloadSize, hdr + 8, 4);

    // Decrypt perm table with master key
    unsigned char perm[LMPK_OPCODE_COUNT];
    for (int i = 0; i < LMPK_OPCODE_COUNT; ++i)
        perm[i] = hdr[16 + i] ^ deobfMK(i % g_mkLen);

    // Build reverse permutation: revPerm[perm[i]] = i
    unsigned char revPerm[LMPK_OPCODE_COUNT];
    memset(revPerm, 0, sizeof(revPerm));
    for (int i = 0; i < LMPK_OPCODE_COUNT; ++i) {
        if (perm[i] < LMPK_OPCODE_COUNT)
            revPerm[perm[i]] = (unsigned char)i;
    }

    // Decrypt XOR key
    unsigned short xkLen;
    memcpy(&xkLen, hdr + 54, 2);
    if (xkLen > LMPK_XOR_KEY_MAX) xkLen = LMPK_XOR_KEY_MAX;
    unsigned char xorKey[LMPK_XOR_KEY_MAX];
    for (int i = 0; i < xkLen; ++i)
        xorKey[i] = hdr[56 + i] ^ deobfMK(i % g_mkLen);

    // Read encrypted payload
    long payloadOffset = fileSize - LMPK_HEADER_SIZE - payloadSize;
    if (payloadOffset < 0) { fclose(f); return -1; }

    unsigned char *payload = (unsigned char *)malloc(payloadSize);
    if (!payload) { fclose(f); return -1; }
    fseek(f, payloadOffset, SEEK_SET);
    if (fread(payload, 1, payloadSize, f) != payloadSize) {
        free(payload); fclose(f); return -1;
    }
    fclose(f);

    // XOR decrypt payload
    for (unsigned int i = 0; i < payloadSize; ++i)
        payload[i] ^= xorKey[i % xkLen];

    // Check if it's bytecode (starts with \033Lua)
    int isBytecode = (payloadSize >= 4 && payload[0] == 0x1b &&
                      payload[1] == 'L' && payload[2] == 'u' && payload[3] == 'a');

    if (isBytecode) {
        // Get size_t width from bytecode header (offset 8)
        int szT = (payloadSize > 8) ? payload[8] : 4;
        // Reverse-remap opcodes back to standard
        int pos = 12; // skip 12-byte luac header
        remapProtoOpcodes(payload, pos, (int)payloadSize, revPerm, szT);
    }

    // Load and execute
    int status = L->LoadBuffer(
        reinterpret_cast<const char*>(payload), payloadSize, "=packed"
    ) || L->TryCall(0, Lumen::RetMul, 0);

    free(payload);
    return status;
}


static int pMain(Lumen::IState *L) {
    auto s = reinterpret_cast<MainArgs *>(L->ToUserdata(1));
    char **argv = s->argv;
    int script;
    int has_i = 0, has_v = 0, has_e = 0;
    globalL = L;
    if (argv[0] && argv[0][0]) programName = argv[0];
    L->GC(Lumen::GCStop, 0);  /* stop collector during initialization */
    L->OpenLibs();  /* open libraries */

#ifdef _WIN32
    loadLightEngine(L);    /* 自动预加载 Light.dll 引擎模块 */
#endif

    L->GC(Lumen::GCRestart, 0);
    s->status = handleLuaInit(L);
    if (s->status != 0) return 0;
    script = collectArgs(argv, &has_i, &has_v, &has_e);
    if (script < 0) {  /* invalid args? */
        printUsage();
        s->status = 1;
        return 0;
    }
    if (has_v) printVersion();
    s->status = runArgs(L, argv, (script > 0) ? script : s->argc);
    if (s->status != 0) return 0;
    if (script)
        s->status = handleScript(L, argv, script);
    if (s->status != 0) return 0;
    if (has_i)
        dotty(L);
    else if (script == 0 && !has_e && !has_v) {
        // No script specified: auto-detect main.lua or lua/main.lua in exe dir
        {
            char exeDir[4096];
            bool gotDir = false;
#ifdef _WIN32
            DWORD edLen = GetModuleFileNameA(nullptr, exeDir, sizeof(exeDir));
            gotDir = (edLen > 0);
#elif defined(__APPLE__)
            uint32_t edSz = sizeof(exeDir);
            gotDir = (_NSGetExecutablePath(exeDir, &edSz) == 0);
#elif defined(__linux__) || defined(__ANDROID__)
            ssize_t edLen = readlink("/proc/self/exe", exeDir, sizeof(exeDir) - 1);
            if (edLen > 0) { exeDir[edLen] = '\0'; gotDir = true; }
#endif
            if (gotDir) {
                char *edSep = strrchr(exeDir, '/');
#ifdef _WIN32
                if (!edSep) edSep = strrchr(exeDir, '\\');
#endif
                if (edSep) *(edSep + 1) = '\0';
                else { exeDir[0] = '.'; exeDir[1] = '/'; exeDir[2] = '\0'; }

                // Set CWD to exe directory
#ifdef _WIN32
                SetCurrentDirectoryA(exeDir);
#else
                (void)chdir(exeDir);
#endif
                // Try main.lua first, then lua/main.lua
                const char *candidates[] = {"main.lua", "lua/main.lua", nullptr};
                for (int ci = 0; candidates[ci]; ++ci) {
                    FILE *fp = fopen(candidates[ci], "r");
                    if (fp) {
                        fclose(fp);
                        s->status = L->DoFile(candidates[ci]);
                        return 0;
                    }
                }
            }

            // Try packed script from exe tail (LMPK format)
            if (loadPackedScript(L) >= 0) {
                return 0;
            }
        }

#if HAS_EMBEDDED_SCRIPTS
        // Fallback: run embedded main.lua script
        s->status = L->LoadBuffer(
            reinterpret_cast<const char*>(g_embed_main_lua),
            g_embed_main_lua_size, "=main.lua"
        ) || L->TryCall(0, Lumen::RetMul, 0);
        return 0;
#else
        if (lua_stdin_is_tty()) {
            printVersion();
            dotty(L);
        } else doFile(L, nullptr);  /* executes stdin as a file */
#endif
    }
    return 0;
}


int main(int argc, char **argv) {
    int status;
    Lumen::IState *L = Lumen::Open();  /* create state */
    if (L == nullptr) {
        luaMessage(argv[0], "cannot create state: not enough memory");
        return EXIT_FAILURE;
    }
    MainArgs s{argc, argv, 0};
    status = L->TryCall(&pMain, &s);
    report(L, status);
    Lumen::Close(L);
    return (status || s.status) ? EXIT_FAILURE : EXIT_SUCCESS;
}

