#!/usr/bin/env python3
"""Convert Lua files to C header with embedded byte arrays.

Usage: python lua2header.py <output.h> <file1.lua> [file2.lua ...]

Each file becomes a const char array + size constant.
Variable names are derived from filenames: main.lua -> g_embed_main_lua
"""
import sys, os, re

def sanitize(name):
    """Filename to C identifier: main.lua -> main_lua"""
    return re.sub(r'[^a-zA-Z0-9]', '_', name)

def convert(filepath):
    name = sanitize(os.path.basename(filepath))
    with open(filepath, 'rb') as f:
        data = f.read()
    lines = []
    lines.append(f"// Embedded from: {os.path.basename(filepath)} ({len(data)} bytes)")
    lines.append(f"static const unsigned char g_embed_{name}[] = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f"    {hex_vals},")
    lines.append("    0x00  // null terminator")
    lines.append("};")
    lines.append(f"static const unsigned int g_embed_{name}_size = {len(data)};")
    return '\n'.join(lines)

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <output.h> <file1.lua> [file2.lua ...]")
        sys.exit(1)
    output = sys.argv[1]
    files = sys.argv[2:]
    guard = sanitize(os.path.basename(output)).upper()
    parts = [
        f"// Auto-generated by lua2header.py - DO NOT EDIT",
        f"#ifndef {guard}",
        f"#define {guard}",
        ""
    ]
    embedded_count = 0
    for f in files:
        if os.path.isfile(f):
            parts.append(convert(f))
            parts.append("")
            embedded_count += 1
    # 告知 light.cpp 是否有内嵌脚本
    parts.append(f"#define HAS_EMBEDDED_SCRIPTS {1 if embedded_count > 0 else 0}")
    parts.append("")
    parts.append(f"#endif // {guard}")
    with open(output, 'w', encoding='utf-8') as out:
        out.write('\n'.join(parts) + '\n')
    print(f"[lua2header] Generated {output} ({len(files)} files)")

if __name__ == '__main__':
    main()
